USE [master]
GO

/****** Object:  Database [HotelBrowser]    Script Date: 01/09/2020 20:32:35 ******/
CREATE DATABASE [HotelBrowser]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HotelBrowser', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\HotelBrowser.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HotelBrowser_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\HotelBrowser_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HotelBrowser].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HotelBrowser] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HotelBrowser] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HotelBrowser] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HotelBrowser] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HotelBrowser] SET ARITHABORT OFF 
GO

ALTER DATABASE [HotelBrowser] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HotelBrowser] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HotelBrowser] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HotelBrowser] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HotelBrowser] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HotelBrowser] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HotelBrowser] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HotelBrowser] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HotelBrowser] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HotelBrowser] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HotelBrowser] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HotelBrowser] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HotelBrowser] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HotelBrowser] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HotelBrowser] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HotelBrowser] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HotelBrowser] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HotelBrowser] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HotelBrowser] SET  MULTI_USER 
GO

ALTER DATABASE [HotelBrowser] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HotelBrowser] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HotelBrowser] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HotelBrowser] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HotelBrowser] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HotelBrowser] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HotelBrowser] SET  READ_WRITE 
GO


